---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.6.0
  - 2.6.2
before_install: gem install bundler -v 1.17.1
env:
  global:
    CC_TEST_REPORTER_ID=fee2a264bfd0ca5458eaed5a28d10a52a04ce412d0eb136f606221dc2d3aff88
services:
  - redis-server
script:
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
branches:
  only:
  - master
