---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.6.0
before_install: gem install bundler -v 1.17.1

services:
  - redis-server

script:
  - bundle exec rake
  - bundle exec rubocop

after_success:
  - bundle exec codeclimate-test-reporter

branches:
  only:
  - master
